'use strict';
const assert=require('node:assert/strict'),plugins=require('../lib/plugins'),render=require('../views/site');
const article=(id,status,publishAt,category='Uutiset')=>({id,slug:id,title:id,status,publishAt,category,text:'Artikkelin teksti',summary:'Ingressi'});
const now=Date.parse('2030-06-01T12:00:00.000Z');
const data=plugins.clean({blog:{enabled:true,posts:[article('luonnos','draft',''),article('heti','published',''),article('tuleva','published','2030-06-01T12:00:01.000Z'),article('nyt','published','2030-06-01T12:00:00.000Z'),article('vanha','published','2030-05-01T00:00:00.000Z','Tiedotteet')]}});
const site={meta:{siteName:'Blogi'},theme:{},navigation:[],footer:{},plugins:data,sections:[{id:'news',type:'blog-list',title:'Ajankohtaista'}]};
const section=options=>plugins.renderSection(site.sections[0],site,options);
assert.deepEqual(section({now}).items.map(x=>x.title),['nyt','vanha','heti']);
assert.equal(section({now:now+1000}).items[0].title,'tuleva');
assert.equal(section({preview:true,now}).items.length,5);
assert.match(section({preview:true,now}).items[0].url,/admin\/esikatselu\?plugin=blog/);
assert.equal(plugins.detail(site,'blog','tuleva',{now}),null);
assert.equal(plugins.detail(site,'blog','luonnos',{now}),null);
assert.ok(plugins.detail(site,'blog','luonnos',{preview:true,now}));
assert.ok(plugins.detail(site,'blog','tuleva',{now:now+1000}));
assert.equal(plugins.publicDetail(site,'/ajankohtaista/luonnos'),null);
assert.match(render(plugins.detail(site,'blog','heti',{now})),/Artikkelin teksti/);
assert.deepEqual(plugins.renderSection({...site.sections[0],pluginData:{category:'Tiedotteet'}},site,{now}).items.map(x=>x.title),['vanha']);
for(const invalid of ['bad','2030-02-30T00:00:00.000Z','2030-06-01T12:00'])assert.throws(()=>plugins.clean({blog:{enabled:true,posts:[article('bad','published',invalid)]}}));
assert.throws(()=>plugins.clean({blog:{posts:[article('bad','unknown','')]}}));
const disabled={...site,plugins:{blog:{...data.blog,enabled:false}}};assert.equal(plugins.renderSection(site.sections[0],disabled,{}),null);assert.equal(plugins.detail(disabled,'blog','heti'),null);
console.log('Blog tests OK (draft privacy, timed list/detail visibility, categories, preview, validation)');
