'use strict';
const assert=require('node:assert/strict');
const ai=require('../lib/layout-ai');
const site={builder:{elements:[],sections:[]},meta:{private:'NOT-SENT'},plugins:{secret:'NOT-SENT'}};
const context=ai.prepare(site,{kind:'sections',prompt:'Kolme korttia'});
assert.ok(!context.prompt.includes('NOT-SENT'));
const node={id:'heading',type:'heading',defaults:{value:'Hei'},children:[]};
const template={name:'Testipohja',root:{id:'root',type:'flex',children:[node]}};
const result=ai.validate(JSON.stringify(template),context);
assert.equal(result.template.id,context.id);
assert.equal(site.builder.sections.length,0);
assert.throws(()=>ai.validate('invalid',context),/JSON/);
assert.throws(()=>ai.validate(JSON.stringify({...template,root:{...node,type:'script'}}),context),/tyyppi/);
const edit=ai.prepare({builder:result.builder},{kind:'sections',targetId:context.id,prompt:'Oranssi otsikko'});
const changed=structuredClone(result.template);changed.root.children[0].style.color='#ff8800';
assert.equal(ai.validate(JSON.stringify(changed),edit).template.root.children[0].style.color,'#ff8800');
changed.root.children=[];
assert.throws(()=>ai.validate(JSON.stringify(changed),edit),/sisältökentän/);
const cycle={name:'Cycle',root:{id:'ref',type:'element',ref:context.id}};
assert.throws(()=>ai.validate(JSON.stringify(cycle),context),/puuttuu/);
const html={name:'HTML',root:{id:'html',type:'html',defaults:{value:'<script>alert(1)</script><p onclick="bad()">OK</p>'}}};
assert.equal(ai.validate(JSON.stringify(html),context).template.root.defaults.value,'<p>OK</p>');
assert.throws(()=>ai.prepare(site,{kind:'plugins',prompt:'x'}));
assert.throws(()=>ai.prepare(site,{kind:'elements',targetId:'missing',prompt:'x'}));
console.log('Layout AI validation tests OK');
