'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {validatePages,selectPage}=require('../lib/pages');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'weboiler-pages-'));
process.env.NODE_ENV='test';process.env.ADMIN_USER='test-admin';process.env.ADMIN_PASSWORD='test-password';process.env.SESSION_SECRET='isolated-pages-test-secret-32-characters';
for(const [key,file] of Object.entries({EDITOR_SITE_FILE:'draft.json',LIVE_SITE_FILE:'live.json',MESSAGES_FILE:'messages.json',ANALYTICS_FILE:'analytics.json',ADMIN_AUTH_FILE:'auth.json',MAIL_SETTINGS_FILE:'mail.json',AI_SETTINGS_FILE:'ai.json',UPLOADS_DIR:'uploads'}))process.env[key]=path.join(root,file);
const fixture={meta:{siteName:'Testi',title:'Etusivu',siteUrl:'https://example.test',description:''},theme:{background:'#000000',surface:'#111111',text:'#ffffff',muted:'#aaaaaa',accent:'#ff8800',font:'Arial',headingFont:'Arial',maxWidth:1280,radius:0},sections:[{id:'home-section',type:'text',title:'Vain etusivulla',text:'Hei'}],navigation:[],elements:[],footer:{text:'Testi'}};
fs.writeFileSync(process.env.EDITOR_SITE_FILE,JSON.stringify(fixture));fs.writeFileSync(process.env.LIVE_SITE_FILE,JSON.stringify(fixture));
async function run(){
 const createAI=require('../lib/ai');
 require.cache[require.resolve('../lib/ai')].exports=options=>{
  const ai=createAI(options);
  return {...ai,generate:async(kind,input,structured)=>{
   if(kind==='image')return {src:'/uploads/fixture.png'};
   assert.equal(structured,true);assert.equal(kind,'text');
   if(input.prompt.startsWith('Edit the copy of ONE'))return {text:JSON.stringify({title:'Osion AI-muutos',text:'Tiivistetty sisältö'})};
   if(input.prompt.startsWith('Plan a Weboiler'))return {text:JSON.stringify({siteName:'Vaihesivu',title:'Vaihesivu',description:'',style:'Tumma',elements:[],pages:[{id:'home',slug:'',title:'Etusivu',description:'',sections:[{id:'hero',type:'hero',title:'Avaus',brief:'Avaus',elementIds:[]}]}]})};
   if(input.prompt.startsWith('Create ONE Weboiler'))return {text:JSON.stringify({id:'hero',type:'hero',title:'Vaihetesti',text:'Valmis'})};
   if(input.prompt.startsWith('Improve a website creation brief.'))return {text:JSON.stringify({prompt:'Luo selkeä yhden sivun markkinointisivusto. Käytä vain annettuja tuotetietoja.'})};
   if(input.prompt.startsWith('Create a complete Weboiler'))return {text:JSON.stringify(require('./site-ai-fixture'))};
   if(input.prompt.startsWith('Create a Weboiler theme'))return {text:JSON.stringify({...fixture.theme,accent:'#ee9900',radius:12})};
   return {text:JSON.stringify({name:'AI HTTP testi',root:{id:'ai-root',type:'heading',defaults:{value:'AI ehdotus'},children:[]}})};
  }};
 };
 const server=require('../server').listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  const base='http://127.0.0.1:'+server.address().port;
 try{
  const lockedTheme=await fetch(base+'/admin/teema',{redirect:'manual'});assert.equal(lockedTheme.status,302);assert.equal(lockedTheme.headers.get('location'),'/admin/login');
  const policy=(await fetch(base+'/')).headers.get('content-security-policy');
  assert.match(policy,/frame-src 'self' https:\/\/www.google.com https:\/\/calendly.com https:\/\/buttondown.com;/);
  assert.match(policy,/script-src 'self';/);
  await require('sharp')({create:{width:900,height:600,channels:3,background:'#4488cc'}}).png().toFile(path.join(process.env.UPLOADS_DIR,'fixture.png'));
  const optimized=await fetch(base+'/media/fixture.png/640');assert.equal(optimized.status,200);assert.equal(optimized.headers.get('content-type'),'image/webp');assert.equal((await require('sharp')(Buffer.from(await optimized.arrayBuffer())).metadata()).width,640);
  assert.equal((await fetch(base+'/media/fixture.png/777')).status,400);
  assert.equal((await fetch(base+'/media/missing.png/640')).status,404);
  let response=await fetch(base+'/api/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'test-admin',password:'test-password'})});
  const cookie=response.headers.get('set-cookie').split(';')[0];
  assert.equal((await fetch(base+'/admin/tuotteet',{headers:{cookie}})).status,200);
  assert.equal((await fetch(base+'/api/admin/plugins/products/integrations/import',{method:'POST'})).status,401);
  assert.equal((await fetch(base+'/api/admin/plugins/products/integrations/import',{method:'POST',headers:{cookie}})).status,403);
  assert.equal((await fetch(base+'/admin/teema',{headers:{cookie}})).status,200);
  const adminSource=fs.readFileSync(path.join(__dirname,'../public/admin.js'),'utf8');
  const themeUI={app:{innerHTML:''},site:fixture,mail:{},auth:{},esc:value=>String(value??''),field:(key)=>`<input data-path="${key}">`};
  const vm=require('node:vm');vm.createContext(themeUI);
  vm.runInContext(adminSource.slice(adminSource.indexOf('function renderTheme()'),adminSource.indexOf('function render(){')),themeUI);
  vm.runInContext('renderTheme()',themeUI);assert.match(themeUI.app.innerHTML,/theme.background/);assert.match(themeUI.app.innerHTML,/theme.maxWidth/);assert.doesNotMatch(themeUI.app.innerHTML,/mail-form/);
  vm.runInContext('renderSettings()',themeUI);assert.doesNotMatch(themeUI.app.innerHTML,/data-path="theme\./);assert.match(themeUI.app.innerHTML,/mail-form/);assert.match(themeUI.app.innerHTML,/meta.siteName/);
  let snapshot=await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json();
  const headers=()=>({cookie,'content-type':'application/json','x-csrf-token':snapshot.csrf,'x-site-version':snapshot.version});
  assert.equal((await fetch(base+'/api/admin/ai/layout',{method:'POST'})).status,401);
  assert.equal((await fetch(base+'/api/admin/ai/layout',{method:'POST',headers:{cookie}})).status,403);
  const draftBefore=fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),liveBefore=fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8');
  assert.equal((await fetch(base+'/api/admin/ai/section',{method:'POST'})).status,401);
  assert.equal((await fetch(base+'/api/admin/ai/section',{method:'POST',headers:{cookie}})).status,403);
  const sectionRequest={pageId:'home',sectionId:'home-section',prompt:'Tiivistä'};
  const sectionResponse=await fetch(base+'/api/admin/ai/section',{method:'POST',headers:headers(),body:JSON.stringify(sectionRequest)});
  assert.equal(sectionResponse.status,200);const sectionProposal=await sectionResponse.json();
  assert.equal(sectionProposal.section.id,'home-section');assert.match(sectionProposal.preview,/Osion AI-muutos/);
  assert.equal((await fetch(base+'/api/admin/ai/section',{method:'POST',headers:{...headers(),'x-site-version':'stale'},body:JSON.stringify(sectionRequest)})).status,409);
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),draftBefore);assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),liveBefore);
  const generated=await fetch(base+'/api/admin/ai/layout',{method:'POST',headers:headers(),body:JSON.stringify({kind:'sections',prompt:'Otsikko'})});
  assert.equal(generated.status,200);const proposal=await generated.json();assert.match(proposal.preview,/AI ehdotus/);assert.equal(proposal.template.name,'AI HTTP testi');
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),draftBefore);assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),liveBefore);
  assert.equal((await fetch(base+'/api/admin/ai/layout',{method:'POST',headers:{...headers(),'x-site-version':'stale'},body:JSON.stringify({kind:'sections',prompt:'Otsikko'})})).status,409);
  assert.equal((await fetch(base+'/api/admin/ai/theme',{method:'POST'})).status,401);
  assert.equal((await fetch(base+'/api/admin/ai/theme',{method:'POST',headers:{cookie}})).status,403);
  const themed=await fetch(base+'/api/admin/ai/theme',{method:'POST',headers:headers(),body:JSON.stringify({prompt:'Oranssi teema'})});
  assert.equal(themed.status,200);const themeProposal=await themed.json();assert.equal(themeProposal.theme.accent,'#ee9900');assert.match(themeProposal.preview,/#ee9900/);
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),draftBefore);assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),liveBefore);
  assert.equal((await fetch(base+'/api/admin/ai/theme',{method:'POST',headers:{...headers(),'x-site-version':'stale'},body:JSON.stringify({prompt:'Teema'})})).status,409);
  assert.equal((await fetch(base+'/api/admin/ai/theme',{method:'POST',headers:headers(),body:JSON.stringify({prompt:''})})).status,400);
  const put=site=>fetch(base+'/api/admin/site',{method:'PUT',headers:headers(),body:JSON.stringify(site)});
  const site=structuredClone(snapshot.site);site.pages=[{id:'services',slug:'palvelut',title:'Palvelusivu',description:'Palvelujen kuvaus',sections:[{id:'home-section',type:'text',title:'Vain alasivulla',text:'Palvelut'}]}];
  site.meta.shareImage='/uploads/fixture.png';site.meta.shareImageAlt='Sivuston oletus';site.pages[0].shareImage='/uploads/page.png';site.pages[0].shareImageAlt='Oma jakokuva';
  site.navigation=[{label:'Koti',target:'/'},{label:'Palvelut',target:'/palvelut'},{label:'Etusivun osio',target:'home-section'}];
  site.plugins={references:{enabled:true,projects:[{id:'test-project',slug:'koekohde',title:'Koekohde',text:'Projektin koko esittely'}]}};
  site.sections.push({id:'refs',type:'references-grid',title:'Referenssit'});
  response=await put(site);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  assert.equal((await fetch(base+'/palvelut')).status,404,'Unpublished page must not be public');
  assert.equal((await fetch(base+'/referenssit/koekohde')).status,404);
  assert.equal((await fetch(base+'/api/admin/plugins')).status,401);
  assert.equal((await fetch(base+'/api/admin/plugins',{headers:{cookie}})).status,200);
  response=await fetch(base+'/admin/esikatselu?plugin=references&item=koekohde',{headers:{cookie}});assert.equal(response.status,200);assert.match(await response.text(),/Projektin koko esittely/);
  assert.equal((await fetch(base+'/admin/esikatselu?plugin=references&item=koekohde',{redirect:'manual'})).status,302);
  response=await fetch(base+'/admin/esikatselu?page=palvelut',{headers:{cookie}});assert.equal(response.status,200);
  const draft=await response.text();assert.match(draft,/Vain alasivulla/);assert.doesNotMatch(draft,/Vain etusivulla/);assert.match(draft,/\/admin\/esikatselu\?page=palvelut/);
  assert.equal((await fetch(base+'/admin/esikatselu?page=missing',{headers:{cookie}})).status,404);
  for(const mutate of [s=>s.pages.push({...s.pages[0],id:'other'}),s=>s.pages[0].slug='admin',s=>s.pages[0].slug='../secret',s=>s.pages[0].id='home',s=>s.pages[0].sections.push({...s.pages[0].sections[0]})]){
    const invalid=structuredClone(site);mutate(invalid);assert.equal((await put(invalid)).status,400);
  }
  response=await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'});assert.equal(response.status,200);
  const live=await (await fetch(base+'/palvelut')).text();assert.match(live,/<title>Palvelusivu<\/title>/);assert.match(live,/https:\/\/example.test\/palvelut/);assert.match(live,/href="\/palvelut"/);assert.match(live,/href="\/#home-section"/);assert.doesNotMatch(live,/Vain etusivulla/);
  assert.match(await (await fetch(base+'/')).text(),/Vain etusivulla/);
  assert.match(live,/<meta property="og:image" content="https:\/\/example.test\/uploads\/page.png">/);
  assert.match(live,/<meta property="og:image:alt" content="Oma jakokuva">/);
  response=await fetch(base+'/referenssit/koekohde');assert.equal(response.status,200);assert.match(await response.text(),/Projektin koko esittely/);
  const history=await (await fetch(base+'/api/admin/history',{headers:{cookie}})).json();
  const published=history.entries.find(entry=>entry.kind==='published');
  response=await fetch(base+`/admin/historia/${published.id}?page=palvelut`,{headers:{cookie}});assert.equal(response.status,200);assert.match(await response.text(),new RegExp('/admin/historia/'+published.id+'\\?page=palvelut'));
  const removed={...snapshot.site,pages:[]};response=await put(removed);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  assert.equal((await fetch(base+'/palvelut')).status,200,'Draft deletion must not delete live page');
  await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'});assert.equal((await fetch(base+'/palvelut')).status,404);
  response=await fetch(base+`/api/admin/history/${published.id}/restore`,{method:'POST',headers:headers(),body:'{}'});assert.equal(response.status,200);assert.equal((await response.json()).site.pages[0].slug,'palvelut');
  assert.deepEqual(validatePages(undefined,x=>x),[]);assert.equal(selectPage(fixture),fixture);
  fs.copyFileSync(path.join(process.env.UPLOADS_DIR,'fixture.png'),path.join(process.env.UPLOADS_DIR,'page.png'));
  snapshot=await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json();
  assert.equal((await fetch(base+'/api/admin/export')).status,401);
  assert.equal((await fetch(base+'/admin/siirto',{headers:{cookie}})).status,200);
  const bundle=await (await fetch(base+'/api/admin/export',{headers:{cookie}})).json();assert.equal(bundle.assets.length,2);
  bundle.site.meta.title='Tuontitesti';bundle.site.apiKey='must-not-survive';
  const upload=()=>{const data=new FormData();data.append('bundle',new Blob([JSON.stringify(bundle)],{type:'application/json'}),'site.json');return data;};
  const importHeaders={cookie,'x-csrf-token':snapshot.csrf,'x-site-version':snapshot.version};
  assert.equal((await fetch(base+'/api/admin/import/apply',{method:'POST',headers:{cookie},body:upload()})).status,403);
  const beforeLive=fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8');
  response=await fetch(base+'/api/admin/import/inspect',{method:'POST',headers:importHeaders,body:upload()});assert.equal(response.status,200);assert.equal((await response.json()).summary.images,2);
  response=await fetch(base+'/api/admin/import/apply',{method:'POST',headers:importHeaders,body:upload()});assert.equal(response.status,200);const imported=await response.json();assert.equal(imported.site.meta.title,'Tuontitesti');assert.equal(imported.site.apiKey,undefined);
  assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),beforeLive);
  assert.equal((await fetch(base+imported.site.meta.shareImage)).status,200);
  assert.equal((await fetch(base+'/api/admin/import/apply',{method:'POST',headers:importHeaders,body:upload()})).status,409);
  snapshot=await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json();
  const blogSite=structuredClone(snapshot.site);blogSite.plugins.blog={enabled:true,posts:[{id:'now',slug:'nyt',title:'Julkinen artikkeli',status:'published',text:'Julkisen artikkelin sisältö'},{id:'later',slug:'myohemmin',title:'Ajastettu salainen',status:'published',publishAt:'9999-01-01T00:00:00.000Z'},{id:'draft',slug:'luonnos',title:'Artikkeliluonnos',status:'draft'}]};blogSite.sections.push({id:'news',type:'blog-list',title:'Uutiset'});
  response=await put(blogSite);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  assert.equal((await fetch(base+'/ajankohtaista/nyt')).status,404);
  assert.equal((await fetch(base+'/admin/esikatselu?plugin=blog&item=myohemmin',{redirect:'manual'})).status,302);
  for(const slug of ['myohemmin','luonnos'])assert.equal((await fetch(base+'/admin/esikatselu?plugin=blog&item='+slug,{headers:{cookie}})).status,200);
  assert.equal((await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'})).status,200);
  const home=await (await fetch(base+'/')).text();assert.match(home,/Julkinen artikkeli/);assert.doesNotMatch(home,/Ajastettu salainen|Artikkeliluonnos/);
  assert.match(await (await fetch(base+'/ajankohtaista/nyt')).text(),/Julkisen artikkelin sisältö/);
  for(const slug of ['myohemmin','luonnos'])assert.equal((await fetch(base+'/ajankohtaista/'+slug)).status,404);
  snapshot=await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json();
  const formSite=structuredClone(snapshot.site);formSite.sections.push({id:'custom-contact',type:'contact',title:'Tarjouspyyntö',form:{recipient:'form@example.test',fields:[{id:'topic',label:'Aihe',type:'select',options:['Tarjous','Kysymys'],required:true},{id:'email',label:'Sähköposti',type:'email',required:true}]}});
  response=await put(formSite);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  const sendForm=values=>fetch(base+'/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({formId:'custom-contact',values,recipient:'ignored@example.test'})});
  assert.equal((await sendForm({topic:'Tarjous',email:'reply@example.test'})).status,400);
  assert.equal((await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'})).status,200);
  const formHtml=await (await fetch(base+'/')).text();assert.match(formHtml,/data-form-id="custom-contact"/);assert.doesNotMatch(formHtml,/form@example.test/);
  assert.equal((await sendForm({topic:'Forged',email:'reply@example.test'})).status,400);
  assert.equal((await sendForm({topic:'Tarjous',email:'reply@example.test'})).status,201);
  const savedMessages=JSON.parse(fs.readFileSync(process.env.MESSAGES_FILE));assert.equal(savedMessages[0].formTitle,'Tarjouspyyntö');assert.equal(savedMessages[0].answers[0].value,'Tarjous');assert.equal(savedMessages[0].email,'reply@example.test');
  snapshot=await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json();
  const languageSite=structuredClone(snapshot.site);languageSite.pages.push({id:'english-home',slug:'en',title:'English home',locale:'en',translationGroup:'home',navigation:[{label:'Contact us',target:'#contact'}],footerText:'English footer',sections:[{id:'contact',type:'contact',title:'Contact'}]});
  response=await put(languageSite);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  assert.equal((await fetch(base+'/en')).status,404);
  const languagePreview=await (await fetch(base+'/admin/esikatselu?page=en',{headers:{cookie}})).text();assert.match(languagePreview,/<html lang="en"/);assert.match(languagePreview,/Contact us/);assert.match(languagePreview,/\/admin\/esikatselu\?page=en/);
  assert.equal((await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'})).status,200);
  const englishHtml=await (await fetch(base+'/en')).text();assert.match(englishHtml,/<html lang="en"/);assert.match(englishHtml,/English footer/);assert.match(englishHtml,/hreflang="fi"/);assert.match(englishHtml,/>Send<\/button>/);
  const duplicateLanguage=structuredClone(languageSite);duplicateLanguage.pages.push({...duplicateLanguage.pages.at(-1),id:'english-duplicate',slug:'en-duplicate'});assert.equal((await put(duplicateLanguage)).status,400);
  snapshot=await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json();
  const contentSite=structuredClone(snapshot.site);contentSite.plugins.content={enabled:true,plans:[{id:'plan',title:'Testipaketti',price:'100 €'}],questions:[{id:'question',title:'Testikysymys',text:'Testivastaus'}],reviews:[{id:'review',title:'Testiasiakas',text:'Testipalaute'}],people:[{id:'person',title:'Testihenkilö',role:'Testirooli'}]};
  contentSite.sections.push(...['pricing-list','faq-list','testimonials-list','team-list'].map((type,index)=>({id:'content-'+index,type,title:type})));
  response=await put(contentSite);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  assert.doesNotMatch(await (await fetch(base+'/')).text(),/Testipaketti/);
  assert.match(await (await fetch(base+'/admin/esikatselu',{headers:{cookie}})).text(),/Testipaketti/);
  assert.equal((await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'})).status,200);
  const contentHtml=await (await fetch(base+'/')).text();for(const marker of ['Testipaketti','Testivastaus','Testipalaute','Testihenkilö'])assert.ok(contentHtml.includes(marker));
  const fullBundle=await (await fetch(base+'/api/admin/export',{headers:{cookie}})).json();assert.equal(fullBundle.site.plugins.content.people[0].title,'Testihenkilö');assert.equal(fullBundle.site.pages.at(-1).locale,'en');assert.equal(fullBundle.site.sections.find(x=>x.id==='custom-contact').form.recipient,'form@example.test');
  const fullUpload=new FormData();fullUpload.append('bundle',new Blob([JSON.stringify(fullBundle)],{type:'application/json'}),'full.json');
  response=await fetch(base+'/api/admin/import/inspect',{method:'POST',headers:{cookie,'x-csrf-token':snapshot.csrf},body:fullUpload});assert.equal(response.status,200);
  snapshot={...snapshot,...await (await fetch(base+'/api/admin/session',{headers:{cookie}})).json()};
  const layoutSite=structuredClone(snapshot.site);layoutSite.builder={elements:[],sections:[{id:'template',name:'Testipohja',root:{id:'heading',type:'heading',defaults:{value:'Pohjan oletus'},children:[]}}]};layoutSite.sections.push({id:'layout',type:'custom',templateId:'template',content:{heading:{value:'Oma sisältö'}}});
  response=await put(layoutSite);assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};
  assert.doesNotMatch(await (await fetch(base+'/')).text(),/Oma sisältö/);
  assert.match(await (await fetch(base+'/admin/esikatselu',{headers:{cookie}})).text(),/Oma sisältö/);
  assert.equal((await fetch(base+'/admin/rakenne-esikatselu?kind=sections&id=template',{redirect:'manual'})).status,302);
  assert.match(await (await fetch(base+'/admin/rakenne-esikatselu?kind=sections&id=template',{headers:{cookie}})).text(),/Pohjan oletus/);
  assert.equal((await fetch(base+'/api/admin/publish',{method:'POST',headers:headers(),body:'{}'})).status,200);
  assert.match(await (await fetch(base+'/')).text(),/Oma sisältö/);
  const layoutBundle=await (await fetch(base+'/api/admin/export',{headers:{cookie}})).json();assert.equal(layoutBundle.site.builder.sections[0].id,'template');
  const beforeWizard=fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),liveWizard=fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8');
  const wizardPost=(suffix,data,extra={})=>fetch(base+'/api/admin/ai/site'+suffix,{method:'POST',headers:{...headers(),...extra},body:JSON.stringify(data)});
  assert.equal((await fetch(base+'/api/admin/ai/site/enhance',{method:'POST'})).status,401);
  assert.equal((await fetch(base+'/api/admin/ai/site/enhance',{method:'POST',headers:{cookie}})).status,403);
  assert.equal((await wizardPost('/enhance',{prompt:''})).status,400);
  response=await wizardPost('/enhance',{prompt:'WEBOILER markkinointisivu',provider:'gemini'});assert.equal(response.status,200);assert.match((await response.json()).prompt,/markkinointisivusto/);
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),beforeWizard);assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),liveWizard);
  assert.equal((await fetch(base+'/api/admin/ai/site',{method:'POST'})).status,401);
  assert.equal((await fetch(base+'/api/admin/ai/site',{method:'POST',headers:{cookie}})).status,403);
  assert.equal((await wizardPost('',{prompt:'Testi'},{'x-site-version':'stale'})).status,409);
  response=await wizardPost('',{prompt:'Testisivusto'});assert.equal(response.status,200);const wizard=await response.json();
  assert.equal(wizard.previews.length,2);assert.equal(wizard.images.length,2);assert.match(wizard.previews[0].html,/placehold.co/);
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),beforeWizard);
  assert.equal((await wizardPost('/apply',{token:wizard.token})).status,400);
  assert.equal((await wizardPost('/image',{token:wizard.token,imageId:'missing',prompt:'kuva'})).status,400);
  response=await wizardPost('/image',{token:wizard.token,imageId:wizard.images[0].id,prompt:'Kuvitus'});assert.equal(response.status,200);const withImage=await response.json();assert.equal(withImage.images[0].src,'/uploads/fixture.png');assert.match(withImage.images[1].src,/placehold.co/);
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),beforeWizard);
  response=await wizardPost('/apply',{token:wizard.token,confirm:true});assert.equal(response.status,200);snapshot={...snapshot,...await response.json()};assert.equal(snapshot.site.meta.siteName,'Velhotesti');assert.equal(snapshot.site.sections[0].image,'/uploads/fixture.png');
  assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),liveWizard);
  assert.equal((await wizardPost('/apply',{token:wizard.token,confirm:true})).status,400);
  const wizardHistory=await (await fetch(base+'/api/admin/history',{headers:{cookie}})).json();assert.ok(wizardHistory.entries.some(e=>e.kind==='before-import'));
  response=await wizardPost('',{prompt:'Toinen'});const staleWizard=await response.json();
  response=await put({...snapshot.site,footer:{text:'Changed after generation'}});snapshot={...snapshot,...await response.json()};
  assert.equal((await wizardPost('/apply',{token:staleWizard.token,confirm:true})).status,409);
  const workflowPost=(suffix,data)=>fetch(base+'/api/admin/ai/workflows'+suffix,{method:'POST',headers:headers(),body:JSON.stringify(data)});
  assert.equal((await fetch(base+'/api/admin/ai/workflows')).status,401);
  assert.equal((await fetch(base+'/api/admin/ai/workflows',{method:'POST',headers:{cookie}})).status,403);
  const beforeStages=fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8');
  response=await workflowPost('',{prompt:'Vaihetesti'});assert.equal(response.status,200);let job=await response.json();
  response=await workflowPost('/'+job.id+'/step',{expectedStep:0});job=await response.json();assert.equal(job.status,'review');
  response=await workflowPost('/'+job.id+'/approve',{plan:job.plan});job=await response.json();
  while(job.status!=='ready'){response=await workflowPost('/'+job.id+'/step',{expectedStep:job.completed});assert.equal(response.status,200);job=await response.json();}
  assert.ok(job.proposal.previews[0].html.includes('Vaihetesti'));
  assert.equal(fs.readFileSync(process.env.EDITOR_SITE_FILE,'utf8'),beforeStages);
  response=await wizardPost('/apply',{token:job.proposal.token,confirm:true});assert.equal(response.status,200);
  assert.equal(fs.readFileSync(process.env.LIVE_SITE_FILE,'utf8'),liveWizard);
  const finished=await (await fetch(base+'/api/admin/ai/workflows/'+job.id,{headers:{cookie}})).json();assert.equal(finished.status,'applied');
  console.log('Pages tests OK (including staged AI routes, approval, assembly and draft/live isolation)');
 }finally{await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
}
run().catch(error=>{console.error(error);process.exitCode=1;});
