'use strict';
const assert=require('node:assert/strict'),helper=require('../lib/section-ai'),layout=require('../lib/layout-builder');
const site=structuredClone(require('./site-ai-fixture'));site.builder=layout.clean(site.builder);
site.sections[1].content={'ref-card-text':{value:'Osion oma teksti',image:'',alt:'',url:''}};
const before=JSON.stringify(site);
const context=helper.prepare(site,{pageId:'home',sectionId:'cards',prompt:'Kolme palstaa ja tiiviimpi teksti'});
assert.ok(!context.prompt.includes('service-text'));
assert.match(context.prompt,/Osion oma teksti/);
assert.equal(context.context.builder.elements.length,0);
const candidate=structuredClone(context.context.original);candidate.root.style.gap=30;
const result=helper.validate(JSON.stringify(candidate),context,site,x=>({...x,builder:layout.clean(x.builder)}));
assert.notEqual(result.template.id,'cards');assert.deepEqual(result.section.content,{});
assert.equal(result.template.root.style.gap,30);assert.equal(JSON.stringify(site),before);
assert.throws(()=>helper.validate(JSON.stringify({...candidate,root:{id:'new',type:'text'}}),context,site,x=>x));
const native=helper.prepare(site,{pageId:'services',sectionId:'service-text',prompt:'Tiivistä'});
assert.equal(helper.validate('{"title":"Uusi otsikko"}',native,site,x=>x).section.title,'Uusi otsikko');
assert.throws(()=>helper.validate('{"type":"contact"}',native,site,x=>x));
assert.throws(()=>helper.prepare(site,{pageId:'home',sectionId:'service-text',prompt:'Muuta'}));
assert.throws(()=>helper.prepare(site,{pageId:'home',sectionId:'hero',prompt:''}));
site.sections.push({id:'contact',type:'contact',form:{recipient:'private@example.test'},email:'secret@example.test',title:'Ota yhteyttä'});
const contact=helper.prepare(site,{pageId:'home',sectionId:'contact',prompt:'Tiivistä'});
assert.ok(!contact.prompt.includes('private@example.test'));assert.ok(!contact.prompt.includes('secret@example.test'));
assert.deepEqual(helper.validate('{"title":"Kirjoita meille"}',contact,site,x=>x).section.form,site.sections[2].form);
console.log('Section AI tests OK (instance isolation, overrides, native fields, privacy, validation)');
