'use strict';
const assert=require('node:assert/strict');
const seo=require('../lib/seo');
const {validatePages,selectPage}=require('../lib/pages');
const render=require('../views/site');
const site={meta:{siteName:'Testi & yritys',title:'Etusivu',description:'Etusivun kuvaus',siteUrl:'https://example.test',shareImage:'/uploads/default.jpg',shareImageAlt:'Oletuskuva'},theme:{},navigation:[],sections:[],footer:{},pages:[{id:'page',slug:'palvelut',title:'Palvelut',seoTitle:'Remontit & palvelut',description:'Oma kuvaus',shareImage:'/uploads/page.jpg',shareImageAlt:'Palvelukuva',sections:[]}]};
const page=selectPage(site,'palvelut'),html=render(page);
assert.match(html,/<title>Remontit &amp; palvelut<\/title>/);
assert.match(html,/<meta property="og:title" content="Remontit &amp; palvelut">/);
assert.match(html,/<meta property="og:image" content="https:\/\/example.test\/uploads\/page.jpg">/);
assert.match(html,/<meta property="og:image:alt" content="Palvelukuva">/);
assert.match(html,/<link rel="canonical" href="https:\/\/example.test\/palvelut">/);
assert.match(html,/<meta name="twitter:card" content="summary_large_image">/);
assert.equal((html.match(/<title>/g)||[]).length,1);
assert.match(render(page,{preview:true}),/<meta name="robots" content="noindex, nofollow">/);
assert.doesNotMatch(html,/<meta name="robots"/);
const fallback=structuredClone(site);fallback.pages[0].shareImage='';fallback.pages[0].seoTitle='';
const inherited=selectPage(fallback,'palvelut');assert.equal(inherited.meta.shareImage,'/uploads/default.jpg');assert.equal(inherited.meta.shareImageAlt,'Oletuskuva');assert.match(render(inherited),/<title>Palvelut<\/title>/);
const malicious=seo.head({title:'</title><script>alert(1)</script>',siteUrl:'javascript:alert(1)',shareImage:'/uploads/x.jpg'});assert.doesNotMatch(malicious,/<script>/);assert.doesNotMatch(malicious,/rel="canonical"|property="og:image"/);
assert.throws(()=>seo.fields({shareImage:'javascript:alert(1)'}));
assert.match(seo.head({siteUrl:'https://example.test',shareImage:'https://images.example.test/a.jpg?size=large&token=test'}),/a.jpg\?size=large&amp;token=test/);
assert.equal(validatePages(site.pages,x=>x)[0].seoTitle,'Remontit & palvelut');
assert.equal(validatePages(site.pages,x=>x)[0].shareImage,'/uploads/page.jpg');
console.log('SEO tests OK (per-page title, image fallback, absolute URLs, escaping, preview)');
