'use strict';
const plugins = require('../lib/plugins');
const seo = require('../lib/seo');
const images = require('../lib/image-presentation');

const esc = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
const safeUrl = (value = '') => { const url = String(value).trim(); return (/^\/(?!\/)/.test(url) || url.startsWith('#') || /^(https?:\/\/|mailto:|tel:)/i.test(url)) && !/[\x00-\x20\\]/.test(url) ? esc(url.replace(/['"()]/g,character=>`%${character.charCodeAt(0).toString(16)}`)) : '#'; };
const phoneHref = (value = '') => `tel:${String(value).replace(/[^+\d]/g, '')}`;
const paragraphs = (value = '') => esc(value).replace(/\n/g, '<br>');
const icon = (item = {}) => item.icon ? `<i class="fa-solid fa-${esc(item.icon)} content-icon" style="--icon-color:${esc(item.iconColor || 'var(--accent)')};--icon-size:${Number(item.iconSize) || 40}px" aria-hidden="true"></i>` : '';

function imageAttrs(src,position) {
  const set=images.srcset(src);
  return `src="${safeUrl(images.optimized(src))}"${set?` srcset="${esc(set)}" sizes="(max-width: 700px) 100vw, 60vw"`:''} style="object-position:${esc(images.position(position))}"`;
}
function renderSection(section,ui) {
  const id = esc(section.id);
  if(section.type==='content-view')return require('./content-sections')(section,{esc,paragraphs,safeUrl,imageAttrs,phoneHref});
  if(section.type==='external-embed')return `<section id="${id}" class="block"><div class="wrap"><p class="eyebrow">${esc(section.eyebrow)}</p><h2>${esc(section.title)}</h2><div class="external-embed" data-embed-url="${esc(section.embedUrl)}" data-preview-message="${esc(ui.embedPreview)}" data-fallback-message="${esc(ui.embedFallback)}" data-embed-height="${section.embedHeight}" data-embed-title="${esc(section.title||'External content')}"><p>${esc(ui.externalNotice||'Ulkoinen sisältö: lataaminen yhdistää palveluun, joka voi käyttää evästeitä.')}</p><button class="button" type="button" data-load-embed>${esc(ui.loadExternal||'Lataa ulkoinen sisältö')}</button><p><a href="${esc(section.embedUrl)}" target="_blank" rel="noopener noreferrer">${esc(ui.openExternal||'Avaa palvelussa')} ↗</a></p><p class="embed-status" role="status"></p></div></div></section>`;
  if (section.type === 'carousel') return `<section id="${id}" class="block"><div class="wrap"><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h2>${esc(section.title)}</h2><div class="carousel" data-interval="${Number(section.interval)||5}" role="region" aria-roledescription="${esc(ui.carousel)}" aria-label="${esc(section.title)}">${(section.images || []).map((image,index)=>`<figure class="carousel-slide${index===0?' is-active':''}" aria-hidden="${index!==0}">${image.url?`<a href="${safeUrl(image.url)}">`:''}<img ${imageAttrs(image.src,image.imagePosition)} alt="${esc(image.alt)}" loading="${index===0?'eager':'lazy'}">${image.url?'</a>':''}${image.alt?`<figcaption>${esc(image.alt)}</figcaption>`:''}</figure>`).join('')}${(section.images||[]).length>1?`<div class="carousel-controls"><button type="button" data-slide="-1" aria-label="${esc(ui.previous)}">←</button><button type="button" data-pause data-pause-label="${esc(ui.pause)}" data-resume-label="${esc(ui.resume)}">${esc(ui.pause)}</button><button type="button" data-slide="1" aria-label="${esc(ui.next)}">→</button></div>`:''}</div></div></section>`;
  if (section.type === 'hero') return `<section id="${id}" class="block hero"${section.image ? ` style="--hero-image:url('${safeUrl(images.optimized(section.image,1920))}');--hero-image-small:url('${safeUrl(images.optimized(section.image,640))}');background-position:${esc(images.position(section.imagePosition))}"` : ''}><div class="wrap hero-content"><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h1>${esc(section.title)}</h1><p class="lead">${paragraphs(section.text)}</p>${section.buttonLabel ? `<a class="button" href="${safeUrl(section.buttonUrl)}">${esc(section.buttonLabel)}</a>` : ''}</div></section>`;
  if (section.type === 'features') return `<section id="${id}" class="block"><div class="wrap"><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h2>${esc(section.title)}</h2><div class="features">${(section.items || []).map((item) => `<article>${item.image?`<img class="card-image" ${imageAttrs(item.image,item.imagePosition)} alt="${esc(item.imageAlt)}" loading="lazy">`:''}${icon(item)}<h3>${esc(item.title)}</h3><p>${paragraphs(item.text)}</p>${item.url?`<a class="card-link" href="${safeUrl(item.url)}">${esc(item.linkLabel||ui.more)} →</a>`:''}</article>`).join('')}</div></div></section>`;
  if (section.type === 'gallery') return `<section id="${id}" class="block"><div class="wrap"><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h2>${esc(section.title)}</h2><div class="gallery">${(section.images || []).map((image) => `${image.url ? `<a href="${safeUrl(image.url)}">` : ''}<img ${imageAttrs(image.src,image.imagePosition)} alt="${esc(image.alt)}" loading="lazy">${image.url ? '</a>' : ''}`).join('')}</div></div></section>`;
  if (section.type === 'cta') return `<section id="${id}" class="block cta"><div class="wrap"><div><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h2>${esc(section.title)}</h2><p>${paragraphs(section.text)}</p></div><a class="button" href="${safeUrl(section.buttonUrl)}">${esc(section.buttonLabel)}</a></div></section>`;
  if (section.type === 'contact') return `<section id="${id}" class="block contact"><div class="wrap contact-grid"><div><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h2>${esc(section.title)}</h2><p>${paragraphs(section.text)}</p><address>${section.phone ? `<a href="${phoneHref(section.phone)}">${esc(section.phone)}</a>` : ''}${section.email ? `<a href="mailto:${esc(section.email)}">${esc(section.email)}</a>` : ''}</address></div><form${section.form?` data-form-id="${id}"`:''}>${section.form?require('../lib/forms').fieldsHtml(section.form,esc):`<label>${ui.name}<input name="name" required></label><label>${ui.email}<input name="email" type="email"></label><label>${ui.phone}<input name="phone"></label><label>${ui.message}<textarea name="message" required></textarea></label>`}<input class="trap" name="website" tabindex="-1" autocomplete="off"><button class="button" type="submit">${ui.send}</button><p class="form-status" role="status"></p></form></div></section>`;
  return `<section id="${id}" class="block"><div class="wrap"><p class="eyebrow">${esc(section.eyebrow)}</p>${icon(section)}<h2>${esc(section.title)}</h2><div class="richtext">${section.html || paragraphs(section.text)}</div></div></section>`;
}

module.exports = function renderSite(site, options = {}) {
  const theme = site.theme;
  const language=site.language||require('../lib/languages').context(site);
  const ui=require('../lib/ui-text')(language.locale);
  const base=seo.httpUrl(language.baseUrl);
  const alternateHead=!options.preview&&base&&language.links.length>1?language.links.map(link=>`<link rel="alternate" hreflang="${esc(link.locale)}" href="${esc(base.replace(/\/$/,'')+(link.url==='/'?'':link.url))}">`).join(''):'';
  const href = value => {
    const target=String(value||'');
    const url=target.startsWith('/')||target.startsWith('#')||/^[a-z]+:/i.test(target)?target:'/#'+target;
    if(options.preview&&url.startsWith('/')&&!url.startsWith('//')) {
      const [pathname,hash='']=url.split('#');
      const slug=pathname.split('/').filter(Boolean).join('/');
      const plugin=plugins.catalog().find(plugin=>plugin.routePrefix&&pathname.startsWith(plugin.routePrefix));
      if(plugin)return safeUrl((options.previewBase||'/admin/esikatselu')+'?plugin='+plugin.id+'&item='+encodeURIComponent(pathname.slice(plugin.routePrefix.length))+(hash?'#'+hash:''));
      if(!slug||(site.pages||[]).some(p=>p.slug===slug))return safeUrl((options.previewBase||'/admin/esikatselu')+(slug?'?page='+encodeURIComponent(slug):'')+(hash?'#'+hash:''));
    }
    return safeUrl(url);
  };
  const style = `--bg:${theme.background};--surface:${theme.surface};--text:${theme.text};--muted:${theme.muted};--accent:${theme.accent};--font:${theme.font};--heading:${theme.headingFont};--max:${Number(theme.maxWidth)}px;--radius:${Number(theme.radius)}px`;
  return `<!doctype html><html lang="${esc(language.locale)}" style="${esc(style)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${seo.head(site.meta,options)}${alternateHead}<link rel="stylesheet" href="/vendor/fontawesome/css/all.min.css"><link rel="stylesheet" href="/assets/site.css?v=1"><link rel="stylesheet" href="/assets/site-enhancements.css?v=1"><link rel="stylesheet" href="/assets/layout-builder.css?v=1"></head><body${options.preview ? ' data-preview="true"' : ''}><header><a class="brand" href="${href(language.homeUrl)}">${site.meta.logo?`<img src="${safeUrl(site.meta.logo)}" alt="${esc(site.meta.logoAlt||site.meta.siteName)}">`:""}<span>${esc(site.meta.siteName)}</span></a><button class="menu" type="button">${ui.menu}</button><nav>${site.navigation.map((item) => `<a href="${href(item.target)}">${esc(item.label)}</a>`).join('')}${language.links.length>1?`<span class="language-switch" aria-label="Language">${language.links.map(link=>`<a href="${href(link.url)}" lang="${esc(link.locale)}" hreflang="${esc(link.locale)}"${link.current?' aria-current="page"':''}>${esc(link.label)}</a>`).join('')}</span>`:''}</nav></header><main>${site.sections.map(section=>plugins.renderSection(section,site,options)).filter(Boolean).map(section=>section.type==='custom'?require('../lib/layout-builder').render(section,site,item=>{const resolved=plugins.renderSection(item,site,options);return resolved?renderSection(resolved,ui):'';}):renderSection(section,ui)).join('')}</main><footer><span>© ${new Date().getFullYear()} ${esc(site.footer.text)}</span><a href="/admin">${ui.admin}</a></footer><script src="/assets/site.js?v=2" defer></script><script src="/assets/embeds.js?v=1" defer></script></body></html>`;
};
